# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(self.centralwidget)
        self.lblTitle.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.lblTitle.setFont(font)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.lblImg = QtWidgets.QLabel(self.centralwidget)
        self.lblImg.setMinimumSize(QtCore.QSize(640, 480))
        self.lblImg.setStyleSheet("background-color: rgb(25, 25, 25);\n"
"border: 2px solid rgb(90, 90, 90);")
        self.lblImg.setAlignment(QtCore.Qt.AlignCenter)
        self.lblImg.setObjectName("lblImg")
        self.verticalLayout.addWidget(self.lblImg)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblResultTitle = QtWidgets.QLabel(self.centralwidget)
        self.lblResultTitle.setMinimumSize(QtCore.QSize(120, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.lblResultTitle.setFont(font)
        self.lblResultTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblResultTitle.setObjectName("lblResultTitle")
        self.horizontalLayout.addWidget(self.lblResultTitle)
        self.lblResult = QtWidgets.QLabel(self.centralwidget)
        self.lblResult.setMinimumSize(QtCore.QSize(300, 50))
        self.lblResult.setStyleSheet("background-color: white;\n"
"border: 1px solid gray;\n"
"font-size: 18px;\n"
"font-weight: bold;")
        self.lblResult.setAlignment(QtCore.Qt.AlignCenter)
        self.lblResult.setObjectName("lblResult")
        self.horizontalLayout.addWidget(self.lblResult)
        self.btnRecognition = QtWidgets.QPushButton(self.centralwidget)
        self.btnRecognition.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.btnRecognition.setFont(font)
        self.btnRecognition.setObjectName("btnRecognition")
        self.horizontalLayout.addWidget(self.btnRecognition)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Parking AI Recognition"))
        self.lblTitle.setText(_translate("MainWindow", "차량 번호 인식 테스트"))
        self.lblImg.setText(_translate("MainWindow", "Camera"))
        self.lblResultTitle.setText(_translate("MainWindow", "AI 인식 결과"))
        self.lblResult.setText(_translate("MainWindow", "인식 대기"))
        self.btnRecognition.setText(_translate("MainWindow", "인식"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
